version: '3'

services:

  cms:
    image: chembience/wagtail-cms:${DJANGO_APP_VERSION}
    container_name: chembience-wagtail-cms
    volumes:
      - ${DJANGO_APP_HOME}:/home/app
      - ${CHEMBIENCE_SPHERE}:/home/sphere
      - ${CHEMBIENCE_SHARE}:/share
    ports:
       - ${DJANGO_APP_CONNECTION_PORT}:80
    networks:
      - sphere
    environment:
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - CHEMBIENCE_DB_USER
      - CHEMBIENCE_DB_HOST
      - CHEMBIENCE_DB_PORT
      - CHEMBIENCE_DB_PASSWORD
      - APP_VIRTUAL_HOSTNAME=${DJANGO_APP_VIRTUAL_HOSTNAME}
      - VIRTUAL_HOST=${DJANGO_APP_VIRTUAL_HOSTNAME}
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - LETSENCRYPT_TEST
    depends_on:
      - cmsdb
    entrypoint: ["/home/app/docker-entrypoint.sh"]
    command: ["/home/nginx/run.sh"]


  cmsdb:
    image: chembience/db:0.2.8
    container_name: chembience-cmsdb
    volumes:
      - cmsdb_volume:/var/lib/postgresql
    networks:
      - sphere
    environment:
      - DEBUG=false
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - DB_USER=${CHEMBIENCE_DB_USER}
      - DB_PASS=${CHEMBIENCE_DB_PASSWORD}
      - DB_NAME=${CHEMBIENCE_DB_USER}
      - DB_TEMPLATE=
      - DB_EXTENSION=
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    ports:
      - 5432:5432


#  cmsindex1:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
#    container_name: chembience-cmsindex1
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - cmsindex1_volume:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#    networks:
#      - sphere
#
#
#  cmsindex2:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
#    container_name: chembience-cmsindex2
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - cmsindex2_volume:/usr/share/elasticsearch/data
#    networks:
#      - sphere

volumes:
  cmsdb_volume:
  cmsindex1_volume:
    driver: local
  cmsindex2_volume:
    driver: local

networks:
  sphere:
