# Generated by Django 2.1 on 2019-03-27 23:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SpotlightIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('introduction', models.TextField(blank=True, help_text='Text to describe the page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SpotlightOptions',
            fields=[
                ('name', models.CharField(default='Spotlight1', max_length=25, primary_key=True, serialize=False)),
                ('style', models.CharField(choices=[('style1', 'No. 1'), ('style2', 'No. 2'), ('style3', 'No. 3'), ('style4', 'No. 4'), ('style5', 'No. 5'), ('style6', 'No. 6'), ('style7', 'No. 7')], default='style1', max_length=25)),
                ('orientation', models.CharField(choices=[('orient-left', 'left'), ('orient-right', 'right')], default='orient-right', max_length=25)),
                ('color', models.CharField(blank=True, choices=[('none', 'none'), ('invert', 'invert'), ('color1', 'color1'), ('color2', 'color2'), ('color3', 'color3'), ('color4', 'color4'), ('color5', 'color5'), ('color6', 'color6'), ('color7', 'color7')], max_length=25, null=True)),
                ('content_align', models.CharField(blank=True, choices=[('content-align-left', 'left'), ('content-align-center', 'center'), ('content-align-right', 'right')], default='content-align-left', max_length=25, null=True)),
                ('image_position', models.CharField(blank=True, choices=[('image-position-left', 'left'), ('image-position-center', 'center'), ('image-position-right', 'right')], default='image-position-center', max_length=25, null=True)),
                ('onload_fade', models.CharField(blank=True, choices=[('onload-content-fade-up', 'content fade up'), ('onload-content-fade-down', 'content fade down'), ('onload-content-fade-left', 'content fade left'), ('onload-content-fade-right', 'content fade right'), ('onload-content-fade-in', 'content fade in'), ('onload-image-fade-in', 'image fade in')], default='onload-content-fade-up', max_length=25, null=True)),
                ('onscroll_fade', models.CharField(blank=True, choices=[('onscroll-content-fade-up', 'content fade up'), ('onscroll-content-fade-down', 'content fade down'), ('onscroll-content-fade-left', 'content fade left'), ('onscroll-content-fade-right', 'content fade right'), ('onscroll-content-fade-in', 'content fade in'), ('onscroll-image-fade-in', 'image fade in')], default='onscroll-image-fade-in', max_length=25, null=True)),
                ('color_choices', models.CharField(blank=True, choices=[('none', 'none'), ('invert', 'invert'), ('color1', 'color1'), ('color2', 'color2'), ('color3', 'color3'), ('color4', 'color4'), ('color5', 'color5'), ('color6', 'color6'), ('color7', 'color7')], default='color1', max_length=25, null=True)),
            ],
            options={
                'verbose_name_plural': 'Spotlight options',
            },
        ),
        migrations.CreateModel(
            name='SpotlightPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField([('heading_block', wagtail.core.blocks.StructBlock([('heading_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('paragraph_block', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', template='blocks/paragraph_block.html')), ('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('attribution', wagtail.core.blocks.CharBlock(required=False))])), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('attribute_name', wagtail.core.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-s15', template='blocks/embed_block.html'))], blank=True, verbose_name='Page Content')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('spotlight_options', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.SpotlightOptions')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
