# Generated by Django 2.2.1 on 2019-05-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionbutton',
            options={'verbose_name': 'Action Button'},
        ),
        migrations.AlterModelOptions(
            name='actionbuttongroupmember',
            options={'verbose_name': 'Action Button Group'},
        ),
        migrations.AlterModelOptions(
            name='styleoptions',
            options={'verbose_name_plural': 'Styling Options'},
        ),
        migrations.AddField(
            model_name='styleoptions',
            name='invert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='styleoptions',
            name='color',
            field=models.CharField(blank=True, choices=[('invert', 'invert'), ('color0', 'color0'), ('color1', 'color1'), ('color2', 'color2'), ('color3', 'color3'), ('color4', 'color4'), ('color5', 'color5'), ('color6', 'color6'), ('color7', 'color7')], default='color0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='styleoptions',
            name='color_choices',
            field=models.CharField(blank=True, choices=[('invert', 'invert'), ('color0', 'color0'), ('color1', 'color1'), ('color2', 'color2'), ('color3', 'color3'), ('color4', 'color4'), ('color5', 'color5'), ('color6', 'color6'), ('color7', 'color7')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='styleoptions',
            name='content_align',
            field=models.CharField(blank=True, choices=[('content-align-left', 'left'), ('content-align-center', 'center'), ('content-align-right', 'right')], default='content-align-left', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='styleoptions',
            name='image_position',
            field=models.CharField(blank=True, choices=[('image-position-left', 'left'), ('image-position-center', 'center'), ('image-position-right', 'right')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='styleoptions',
            name='name',
            field=models.CharField(default='Spotlight1', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='styleoptions',
            name='onload_fade',
            field=models.CharField(blank=True, choices=[('onload-content-fade-up', 'content fade up'), ('onload-content-fade-down', 'content fade down'), ('onload-content-fade-left', 'content fade left'), ('onload-content-fade-right', 'content fade right'), ('onload-content-fade-in', 'content fade in'), ('onload-image-fade-in', 'image fade in')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='styleoptions',
            name='onscroll_fade',
            field=models.CharField(blank=True, choices=[('onscroll-content-fade-up', 'content fade up'), ('onscroll-content-fade-down', 'content fade down'), ('onscroll-content-fade-left', 'content fade left'), ('onscroll-content-fade-right', 'content fade right'), ('onscroll-content-fade-in', 'content fade in'), ('onscroll-image-fade-in', 'image fade in')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='styleoptions',
            name='orientation',
            field=models.CharField(choices=[('orient-left', 'left'), ('orient-right', 'right')], default='orient-right', max_length=30),
        ),
        migrations.AlterField(
            model_name='styleoptions',
            name='style',
            field=models.CharField(choices=[('style1', 'No. 1'), ('style2', 'No. 2'), ('style3', 'No. 3'), ('style4', 'No. 4'), ('style5', 'No. 5'), ('style6', 'No. 6'), ('style7', 'No. 7')], default='style1', max_length=30),
        ),
    ]
