# Generated by Django 2.1 on 2019-03-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='section_1_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_1_headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
