# Generated by Django 2.2.4 on 2019-08-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='header',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
