# Generated by Django 2.2.1 on 2019-06-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
