# Generated by Django 2.2.4 on 2019-08-16 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionStyling',
            fields=[
                ('coloroptions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='home.ColorOptions')),
                ('stylingbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.StylingBase')),
            ],
            options={
                'verbose_name': 'Section Styling',
            },
            bases=('home.stylingbase', 'home.coloroptions'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='styling_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.SectionStyling'),
        ),
    ]
