# Generated by Django 2.2.1 on 2019-07-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryindexstyling',
            options={'verbose_name': 'Gallery Styling'},
        ),
        migrations.RemoveField(
            model_name='galleryarticlepage',
            name='lightbox_button',
        ),
        migrations.RemoveField(
            model_name='galleryarticlepage',
            name='lightbox_button_text',
        ),
        migrations.AddField(
            model_name='galleryindexstyling',
            name='lightbox_button',
            field=models.BooleanField(default=True, verbose_name='Lightbox Button'),
        ),
        migrations.AddField(
            model_name='galleryindexstyling',
            name='lightbox_button_text',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
