# Generated by Django 2.2.1 on 2019-06-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_button_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionbuttons',
            name='fit',
            field=models.BooleanField(default=False, verbose_name='Fit Buttons'),
        ),
    ]
