# Generated by Django 2.1 on 2019-03-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190328_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlightoptions',
            name='image_position',
            field=models.CharField(blank=True, choices=[('image-position-left', 'left'), ('image-position-center', 'center'), ('image-position-right', 'right')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='spotlightoptions',
            name='onload_fade',
            field=models.CharField(blank=True, choices=[('onload-content-fade-up', 'content fade up'), ('onload-content-fade-down', 'content fade down'), ('onload-content-fade-left', 'content fade left'), ('onload-content-fade-right', 'content fade right'), ('onload-content-fade-in', 'content fade in'), ('onload-image-fade-in', 'image fade in')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='spotlightoptions',
            name='onscroll_fade',
            field=models.CharField(blank=True, choices=[('onscroll-content-fade-up', 'content fade up'), ('onscroll-content-fade-down', 'content fade down'), ('onscroll-content-fade-left', 'content fade left'), ('onscroll-content-fade-right', 'content fade right'), ('onscroll-content-fade-in', 'content fade in'), ('onscroll-image-fade-in', 'image fade in')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='spotlightoptions',
            name='style',
            field=models.CharField(choices=[('style1', 'No. 1'), ('style2', 'No. 2'), ('style3', 'No. 3'), ('style4', 'No. 4'), ('style5', 'No. 5'), ('style6', 'No. 6'), ('style7', 'No. 7')], default='No. 1', max_length=25),
        ),
    ]
