# Generated by Django 2.1 on 2019-03-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190330_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
