# Generated by Django 2.2.4 on 2019-08-16 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190816_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionpage',
            name='styling_options',
        ),
        migrations.AddField(
            model_name='sectionindexpage',
            name='styling_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.SectionStyling'),
        ),
    ]
