# Generated by Django 2.2.1 on 2019-07-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190722_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryindexstyling',
            name='lightbox_button',
        ),
    ]
