# Generated by Django 2.2.4 on 2019-08-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190820_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
