# Generated by Django 2.2.1 on 2019-05-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190519_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleoptions',
            name='color',
            field=models.CharField(blank=True, choices=[('color0', 'Color 0'), ('color1', 'Color 1'), ('color2', 'Color 2'), ('color3', 'Color 3'), ('color4', 'Color 4'), ('color5', 'Color 5'), ('color6', 'Color 6'), ('color7', 'Color 7')], default='color0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='styleoptions',
            name='color_choices',
            field=models.CharField(blank=True, choices=[('color0', 'Color 0'), ('color1', 'Color 1'), ('color2', 'Color 2'), ('color3', 'Color 3'), ('color4', 'Color 4'), ('color5', 'Color 5'), ('color6', 'Color 6'), ('color7', 'Color 7')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='styleoptions',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
