# Generated by Django 2.2.1 on 2019-06-28 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_actionbuttons_fit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerpage',
            old_name='action_buttons',
            new_name='actions',
        ),
    ]
