# Generated by Django 2.1 on 2019-03-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_section_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='section_title',
            new_name='section_1_title',
        ),
    ]
