# Generated by Django 2.2.1 on 2019-06-04 21:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0003_auto_20190519_2039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeStreamPage',
            new_name='StreamPage',
        ),
    ]
