# Generated by Django 2.1 on 2019-03-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190328_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotlightpage',
            old_name='spotlight_options',
            new_name='options',
        ),
    ]
