# Generated by Django 2.2.1 on 2019-06-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190628_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpage',
            name='fullscreen',
            field=models.BooleanField(default=True, verbose_name='Full Screen'),
        ),
    ]
