# Generated by Django 2.1 on 2019-03-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190330_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='section_1_title',
        ),
    ]
