# Generated by Django 2.2.1 on 2019-07-01 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bannerpage_fullscreen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionbutton',
            options={'verbose_name': 'Action Button'},
        ),
        migrations.RenameField(
            model_name='spotlightpage',
            old_name='options',
            new_name='styling_options',
        ),
        migrations.AddField(
            model_name='spotlightpage',
            name='actions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.ActionButtons'),
        ),
    ]
