# Generated by Django 2.2.1 on 2019-07-03 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190701_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryarticlepage',
            name='actions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.ActionButtons'),
        ),
    ]
