# Generated by Django 2.1.7 on 2019-04-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sectionindexpage_sectionpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionindexpage',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
