# Generated by Django 2.2.1 on 2019-07-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_galleryarticlepage_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotlightindexpage',
            name='introduction',
        ),
    ]
