# Generated by Django 2.2.1 on 2019-07-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_spotlightindexpage_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryarticlepage',
            name='lightbox_button',
            field=models.BooleanField(default=True, verbose_name='Lightbox Button'),
        ),
        migrations.AddField(
            model_name='galleryarticlepage',
            name='lightbox_button_text',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
