# Generated by Django 2.2.1 on 2019-07-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190704_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempage',
            name='actions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.ActionButtons'),
        ),
    ]
