# Generated by Django 2.2.4 on 2019-10-15 22:04

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191011_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempage',
            name='headline',
        ),
        migrations.AlterField(
            model_name='itempage',
            name='text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
