# Generated by Django 2.1.7 on 2019-04-14 22:08

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_bannerpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpage',
            name='major',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Major Text'),
        ),
        migrations.AlterField(
            model_name='bannerpage',
            name='minor',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Minor Text'),
        ),
    ]
