# Generated by Django 2.1.7 on 2019-04-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190414_2208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpotlightOptions',
            new_name='VisualStyleOptions',
        ),
    ]
