# Generated by Django 2.2 on 2019-04-27 21:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_itemindexpage_itempage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=255)),
                ('size', models.CharField(blank=True, choices=[('', 'Default'), ('small', 'Small')], default='', max_length=25)),
                ('icon', models.CharField(blank=True, default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='BannerPageActionButtons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.ActionButton')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_buttons', to='home.BannerPage')),
            ],
            options={
                'verbose_name': 'action button',
                'verbose_name_plural': 'action buttons',
            },
        ),
    ]
