# Generated by Django 2.2 on 2019-04-27 21:57

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_actionbutton_bannerpageactionbuttons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpageactionbuttons',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='home.BannerPage'),
        ),
    ]
