# Generated by Django 2.2 on 2019-04-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190427_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpageactionbuttons',
            name='fit',
            field=models.BooleanField(default=False),
        ),
    ]
