# Generated by Django 2.2 on 2019-04-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_bannerpageactionbuttons_fit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerpageactionbuttons',
            name='fit',
        ),
    ]
