# Generated by Django 2.2 on 2019-04-28 21:48

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_bannerpageactionbuttons_fit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionButtonGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('small', models.BooleanField(default=False, verbose_name='Small Buttons')),
                ('stacked', models.BooleanField(default=False, verbose_name='Stacked Buttons')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='action_buttons_small',
            field=models.BooleanField(default=False, verbose_name='Small Action Buttons'),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='action_buttons_stacked',
            field=models.BooleanField(default=False, verbose_name='Stacked Action Buttons'),
        ),
        migrations.AlterField(
            model_name='actionbutton',
            name='size',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('small', 'Small'), ('large', 'Large')], default='', max_length=25),
        ),
        migrations.CreateModel(
            name='ActionButtonGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.ActionButton')),
                ('group', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='home.ActionButtonGroup')),
            ],
            options={
                'verbose_name': 'action button group',
            },
        ),
    ]
