# Generated by Django 2.2 on 2019-04-28 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190428_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerpage',
            name='action_buttons_small',
        ),
        migrations.RemoveField(
            model_name='bannerpage',
            name='action_buttons_stacked',
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='actions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.ActionButtonGroup'),
        ),
        migrations.DeleteModel(
            name='BannerPageActionButtons',
        ),
    ]
