# Generated by Django 2.2 on 2019-04-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20190428_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerpage',
            old_name='actions',
            new_name='button_group',
        ),
    ]
