# Generated by Django 2.2 on 2019-04-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20190428_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='section_1',
            new_name='banner_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_1_headline',
        ),
    ]
