# Generated by Django 2.2 on 2019-05-03 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_homepage_spotlight_index_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='spotlight_index_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Spotlights'),
        ),
    ]
