# Generated by Django 2.2 on 2019-05-05 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('home', '0028_homepage_item_index_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryPage',
            new_name='GalleryIndexPage',
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_index_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Gallery'),
        ),
    ]
