# Generated by Django 2.2 on 2019-05-05 20:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0030_auto_20190505_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBlockPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField([('banner_block', wagtail.core.blocks.PageChooserBlock(page_type=['home.BannerPage'], template='home/templates/banner_include_page.html'))], blank=True, verbose_name='Page Content')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
