# Generated by Django 2.2 on 2019-05-05 21:30

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_homeblockpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeblockpage',
            name='content',
            field=wagtail.core.fields.StreamField([('banner_block', wagtail.core.blocks.PageChooserBlock(page_type=['home.BannerPage'], template='home/banner_include_page.html'))], blank=True, verbose_name='Page Content'),
        ),
        migrations.AlterField(
            model_name='spotlightpage',
            name='content',
            field=models.TextField(blank=True, verbose_name='Page Content'),
        ),
    ]
