# Generated by Django 2.2 on 2019-05-05 21:37

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20190505_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlightpage',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spotlightpage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
