# Generated by Django 2.2 on 2019-05-05 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20190505_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotlightpage',
            name='headline',
        ),
    ]
