# Generated by Django 2.2 on 2019-05-08 23:00

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20190508_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeblockpage',
            name='content',
            field=wagtail.core.fields.StreamField([('banner_block', wagtail.core.blocks.PageChooserBlock(page_type=['home.BannerPage', 'home.SectionIndexPage']))], blank=True, verbose_name='Page Content'),
        ),
    ]
