# Generated by Django 2.2 on 2019-05-09 22:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20190509_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeblockpage',
            name='content',
        ),
        migrations.AddField(
            model_name='homeblockpage',
            name='stream',
            field=wagtail.core.fields.StreamField([('page', wagtail.core.blocks.PageChooserBlock(blank=True, null=True))], default=None),
            preserve_default=False,
        ),
    ]
