# Generated by Django 2.2 on 2019-05-09 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20190509_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeblockpage',
            old_name='stream',
            new_name='content',
        ),
    ]
