# Generated by Django 2.2 on 2019-05-09 23:10

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20190509_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeblockpage',
            name='content',
            field=wagtail.core.fields.StreamField([('banner1', wagtail.core.blocks.PageChooserBlock(blank=True, null=True)), ('section_index1', wagtail.core.blocks.PageChooserBlock(blank=True, null=True))]),
        ),
    ]
