# Generated by Django 2.2 on 2019-05-13 22:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20190509_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeblockpage',
            name='content',
            field=wagtail.core.fields.StreamField([('banner', wagtail.core.blocks.PageChooserBlock(blank=True, null=True, page_type=['home.BannerPage'])), ('section_index', wagtail.core.blocks.PageChooserBlock(blank=True, null=True, page_type=['home.SectionIndexPage'])), ('gallery_index', wagtail.core.blocks.PageChooserBlock(blank=True, null=True, page_type=['home.GalleryIndexPage']))]),
        ),
    ]
